Post-merge cleanup: there seems to be no reason why we should be depending on the git plugin. See #51
Dependency on the git plugin causes the following error during the installation of the Build Monitor:

java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1304)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:104)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.io.IOException: Failed to install build-monitor-plugin plugin
	at hudson.PluginManager.dynamicLoad(PluginManager.java:440)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1300)
	... 6 more
Caused by: java.io.IOException: Dependency git-client (1.0.6) doesn't exist
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:488)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:430)
	... 7 more